### ISSUE TITLE
Some issues about how to reproduce the experimental results of ablation tests

### ISSUE THREAD

**Issue by NLP-hua** [LooperXX/DF-Net#1]
Hello, I am following your work and I can get the result in Table 2 using your released model and script.

However, I don't know how to obtain the results of ablation tests in Table 3.

w/o Domain-Shared Knowledge Transfer
w/o Dynamic Fusion Mechanism 
w/o Multi-Encoder
w/o Multi-Decoder
w/o Adversarial Training

Can u give some suggestions?

best regards

**Comment by LooperXX** [comment]
Hi, @NLP-hua . In Section 3.5.1 of our paper, due to space constraints, we give a brief description of the experimental setup but can provide you with enough information, you can easily modify our source code to obtain different ablation model.
