### ISSUE TITLE
Can you provide the python file (or script) of preprocessing MULTIWOZ2.1 dataset?

### ISSUE THREAD

**Issue by scoyer** [LooperXX/DF-Net#3]
Like what [Mem2Seq](https://github.com/HLTCHKUST/Mem2Seq/blob/master/data/KVR/read_data.py) did.

**Comment by LooperXX** [comment]
I am very sorry that I cannot provide you with the data preprocessing script as our files related to this project on the cloud server have been automatically cleaned by the server for the timeout reason.
If you have any detailed questions about data processing, you can communicate with me via email.
